# Generated by Django 4.2.7 on 2023-12-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grochery', '0004_food_user_food_users_remove_favoritefood_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritefood',
            name='food',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Grochery.food'),
            preserve_default=False,
        ),
    ]
