# Generated by Django 4.2.7 on 2023-12-04 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Grochery', '0005_alter_favoritefood_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglist',
            name='food',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='shopping_lists', to='Grochery.food'),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
